apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sshjump.fullname" . }}
  labels:
    {{- include "sshjump.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sshjump.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sshjump.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sshKeySecret }}
                  key: authorizedkeys
          volumeMounts:
            - name: ssh-server-secrets
              mountPath: /opt/ssh-server-secrets
              readOnly: true
      volumes:
        - name: ssh-server-secrets
          secret:
            secretName: {{ .Values.sshServerKeysSecret }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
