# Default values for gadgetron.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_2004:latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  storageClass: standard
  dependenciesVolumeSize: 5Gi
  dataVolumeSize: 100Gi

service:
  type: ClusterIP
  port: 9002
  annotations: {}
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"

serviceMonitor:
  port: 8080
  labels:
    prometheus: monitor
  interval: 30s

hpa:
  minReplicas: 1
  maxReplicas: 20
  targetInstanceUtilization: 500m

resources:
  # limits:
  #   cpu: 5000m
  #   memory: 128Mi
  # requests:
  #  cpu: 1000m
  #  memory: 1024Mi

nodeSelector: {}

tolerations: []
