apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gadgetron.dependenciesname" . }}
  labels:
{{ include "gadgetron.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.dependenciesVolumeSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gadgetron.dataname" . }}
  labels:
{{ include "gadgetron.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.dataVolumeSize }}
