{{ if .Values.storage.storageServer.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gadgetron.fullname" . }}-storage
  labels:
    {{- include "gadgetron.labels" . | nindent 4 }}
    app: storageServer
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gadgetron.selectorLabels" . | nindent 6 }}
      app: storageServer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        {{- include "gadgetron.selectorLabels" . | nindent 8 }}
        app: storageServer
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-storage
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gadgetron_storage_server", "-D", "/tmp/gadgetron/database", -S, "/tmp/gadgetron/storage" ]
          ports:
          - containerPort: 9112
          volumeMounts:
            - mountPath: "/tmp/gadgetron"
              name: {{ include "gadgetron.dependenciesname" . }}
          resources:
            {{- toYaml .Values.storage.storageServer.resources | nindent 12 }}
      volumes:
      - name: {{ include "gadgetron.dependenciesname" . }}
        persistentVolumeClaim:
          claimName: {{ include "gadgetron.dependenciesname" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
