{{ if .Values.storage.storageServer.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gadgetron.fullname" . }}-storage
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- include "gadgetron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.storage.storageServer.port }}
      targetPort: 9112
      protocol: TCP
      name: gadgetron-storage
  selector:
    {{- include "gadgetron.selectorLabels" . | nindent 4 }}
    app: storageServer
{{ end }}