apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gadgetron.fullname" . }}-storage
spec:
  selector:
    matchLabels:
      component: {{ include "gadgetron.fullname" . }}-storage
  replicas: 1
  template:
    metadata:
      labels:
        component: {{ include "gadgetron.fullname" . }}-storage
    spec:
    {{- with .Values.storageServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-db-ready
          image: jbergknoff/postgresql-client
          command:
            - 'sh'
            - '-c'
            - |
              until pg_isready -U {{ template "postgresql.username" .Subcharts.storagedb }} -d {{ .Values.storagedb.postgresqlDatabase }} -h {{ template "common.names.fullname" .Subcharts.storagedb }} -p 5432; do
                echo waiting for database
                sleep 2
              done
      containers:
        - name: mrd-storage-server
          image: {{ .Values.storageServer.image }}
          imagePullPolicy: {{ .Values.storageServer.imagePullPolicy }}
          env:
            - name: MRD_STORAGE_SERVER_DATABASE_PROVIDER
              value: postgresql
            - name: MRD_STORAGE_SERVER_DATABASE_CONNECTION_STRING
              value: host={{ template "common.names.fullname" .Subcharts.storagedb }} dbname={{ .Values.storagedb.postgresqlDatabase }} port=5432 user={{ template "postgresql.username" .Subcharts.storagedb }}
            - name: MRD_STORAGE_SERVER_DATABASE_PASSWORD_FILE
              value: /etc/secrets/postgresql-password
            - name: MRD_STORAGE_SERVER_STORAGE_PROVIDER
              value: azureblob
            - name: MRD_STORAGE_SERVER_STORAGE_CONNECTION_STRING_FILE
              value: /etc/secrets/storage-connection-string
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3333
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3333
          volumeMounts:
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
          resources:
            {{- toYaml .Values.storageServer.resources | nindent 12 }}
      volumes:
      - name: secrets
        projected:
          sources:
          - secret:
              name: {{ template "common.names.fullname" .Subcharts.storagedb  }}
          - secret:
              name: {{ required "A value for storagedb.storageAccountConnectionStringSecretName" .Values.storageServer.storageAccountConnectionStringSecretName }}
              items:
                - key: {{ .Values.storageServer.storageAccountConnectionStringSecretDataKey }}
                  path: storage-connection-string
      {{- with .Values.storageServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}    
      {{- end }}  
      {{- with .Values.storageServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "gadgetron.fullname" . }}-storage
spec:
  selector:
    component: {{ include "gadgetron.fullname" . }}-storage
  ports:
    - name: storage
      protocol: TCP
      port: 8080
      targetPort: 3333
